/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting(){
            try {
                ArrayList<Quotes> quotes = App.readFile();
                assertEquals(" ““The ''wealth'' of a good heard is SO much better than a thousand beautiful faces.” ”Vasso Charalambous", quotes.get(100).toString());
            } catch (IOException e) {
                System.out.println(e.getMessage());
            }
        }
}
