/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.Random;
public class App {
    public static void main(String[] args) throws IOException {
        System.out.println("hello");
        int value =new Random().nextInt(readFile().size()-1);
        System.out.println(value + "    This is the index");
        System.out.println(readFile().get(value).toString());
    }
    public static ArrayList<Quotes> readFile() throws IOException {
        BufferedReader reader =new BufferedReader(new FileReader("./app/src/main/resources/recentquotes.json"));
        Type quotesArrayList = new TypeToken<ArrayList<quotes.Quotes>>() {}.getType();
        GsonBuilder builder = new GsonBuilder();
        Gson gson = builder.create();
        ArrayList<Quotes> converter = gson.fromJson(reader, quotesArrayList);
    return converter;
    }
}
